#指定服务端口
server:
  port: 8082
#配置dubbo
dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://127.0.0.1
    port: 2181
  scan:
    base-packages: com.example.consumer.controller
  consumer: #关闭启动时检查
    check: false